- algorithms/other/typeScript/bogoSort.ts
Add type-safe algorithm for bogo-sort (aka. monkey-sort) - typeScript
> feat: add bogoSort algorithm in typeScript language

- README.md
- algorithms/cpp/MergeSort.cpp
> Added Merge Sort in C++

- BinarySearch.py
I have implemented binary search in python with sample input value.
> Created BinarySearch.py

- LinearSearch.py
Created a python file for implementation of linear search algorithm
> Linear Search Algorithm - Python

- algorithms/python/BreadthFirstSearch.py
PR with reference to issue #23.
> Created BreadthFirstSearch.py

- algorithms/cpp/HeapSort.cpp
> HeapSort in cpp

- PythonSMTP_Skeleton.py
This is just the basic skeleton code of how to send Mails using Python and SMTP Module. Couldn't really guess in which folder should I've added this too, so here it is. This is for Hacktober fest.
> Sending Mail using Python and SMTP

- algorithms/java/InterpolationSearch.java
I just add Interpolation Search in Java
> Add Interpolation Search in Java #31

- algorithms/cpp/Depth First Traversal in C++
Given a connected undirected graph. Perform a Depth First Traversal of the graph.
Note: Use recursive approach.
Input:
The first line of the input contains an integer 'T' denoting the number of test cases. Then 'T' test cases follow. Each test case consists of two lines. Description of testcases is as follows: The First line of each test case contains two integers 'N' and 'E'  which denotes the no of vertices and no of edges respectively. The Second line of each test case contains 'E'  space separated pairs u and v denoting that there is a edge from u to v .
Output:
For each testcase, print the nodes while doing DFS starting from node 0.
Your task:
You don't need to read input or print anything. Your task is to complete the function dfs() which takes the Graph and the number of vertices …
> Depth First Traversal in C++

- algorithms/python/Dijkstra's_algorithm.py
Implemented **Dijkstra's Algorithm** in Python.
> Dijkstra Algorithm in Python

- algorithms/java/KruskalAlgorithm.java
> Added Kruskal's Minimum Spanning Tree in Java

- README.md
- algorithms/javascript/CountingSort.js
PR for Issue #73 with updated README.md
> Counting Sort in Javascript

- questions/cpp/Matrix_chain_mult.cpp
- questions/cpp/all_sol_of_n_queen.cpp
- questions/cpp/knapsack.cpp
- questions/cpp/knapsack_with_large_weight.cpp
- questions/cpp/knight_tour_backtracking.cpp
- questions/cpp/n_queen.cpp
- questions/cpp/rod_cutting_prob.cpp
- questions/cpp/sub_matrix_with_all_1s.cpp
Added standard problems in Question/cpp folder
> Some standard problems

- algorithms/cpp/Dijkstra.cpp
> Dijkstra's Algorithm in C++

- algorithms/java/BreadthFirstSearch.java
Added BreadthFirstSearch for Java.
> Added BreadthFirstSearch for Java

- algorithms/python/heapsort.py
> Create Heapsort in Python

- boubleSort_visualized.js
this is an visual implementation of bouble sort
> Bouble sort visualized

- data structures/java/queue_using_stack.java
please review and suggest/merge the pull request.
> Implement queue using stack

- data structures/java/DynamicList.java
I added a Dynamic List in java.
> Adding a Dynamic List in Java

- algorithms/cpp/linear search.cpp
program to perform linear search
> linear search

- others/HangManSY.py
> Hangman Game in Python

- data structures/cpp/HeapImplementation.cpp
Added file HeapImplementtion.cpp that implements Max-Heap in C++, along with dynamic insertion and deletion operation in heap.
> Adding solution for Heap Implementation in C++ (Issue id: #126 )

- algorithms/other/typeScript/countingSort.ts
- algorithms/other/typeScript/mergeSort.ts
add bogoSort algorithm in typeScript language.
> feat: add countingSort algorithm in typeScript language

- algorithms/python/Kadane's_Algorithm.py
No errors or bugs. Successfully submitted on Leetcode with a runtime of 64 ms. Thanks for the opportunity to contribute!
> Kadane's Algorithm Added in Python

- data structures/cpp/bst in c++
This is my github profile
https://github.com/Chandanbrajwasi
> Create bst in c++

- algorithms/python/BogoSort.py
> Added BogoSort

- algorithms/C Language/BinarySearch.c
- algorithms/C Language/Factorial.c
- algorithms/C Language/Fibonacci.c
- algorithms/C Language/InsertionSort.c
- algorithms/C Language/MergeSort.c
- algorithms/C Language/TowerOfHanoi.c
- algorithms/C Language/bubble_sort.c
- algorithms/cpp/CheckingAutomorphicNumber.cpp
- algorithms/cpp/CheckingPalindromeNumber.cpp
- algorithms/cpp/Fibonacci.cpp
- algorithms/cpp/TowerOfHanoi.cpp
- algorithms/cpp/binary_search.cpp
Improved some programs and added new programs. Please mark hacktoberfest-accepted during merge.
> Added some programs for CPP and C

- algorithms/java/LinearSearch.java
- algorithms/java/MergeSort.java
- algorithms/java/SelectionSort.java
Hey @sobhanbera I have implemented following languages:
1. Linear Search in Java
2. Merge Sort in Java
3. Quick sort in C
4. Selection sort in java 
Please review & Suggest changes if any.
> Implemented multiple algorithms in yet-uncontributed languages
